HairSalon/Models/Client.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public string Details { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }

    public static List<Client> Search(List<Client> allClients, string searchParam)
    {
      List<Client> matchingClients = new List<Client> { };
      if (searchParam != null)
      {
        foreach (Client client in allClients)
        {
          if (client.Name.ToUpper().Contains(searchParam.ToUpper()))
          {
            matchingClients.Add(client);
          }
        }
      }
      return matchingClients;
    }

  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet <Client> Clients { get; set; }
    public HairSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Specialty { get; set; }
    public string Details { get; set; }
    public virtual ICollection<Client> Clients { get; set; }

    public static List<Stylist> Search(List<Stylist> allStylists, string searchParam)
    {
      List<Stylist> matchingStylists = new List<Stylist> { };
      if (searchParam != null)
      {
        foreach (Stylist stylist in allStylists)
        {
          if (stylist.Name.ToUpper().Contains(searchParam.ToUpper()))
          {
            matchingStylists.Add(stylist);
          }
          else if (stylist.Specialty.ToUpper().Contains(searchParam.ToUpper()))
          {
            matchingStylists.Add(stylist);
          }
        }
      }
      return matchingStylists;
    }

  }
}

HairSalon/Controllers/ClientsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");    
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult Search(string search)
    {
      List<Client> searchList = _db.Clients.Include(clients => clients.Stylist).ToList();
      List<Client> model = Client.Search(searchList, search);
      return View(model);
    }

  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

HairSalon/Controllers/StylistsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists
      .Include(stylist => stylist.Clients)
      .FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    public ActionResult Edit(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult Search(string search)
    {
      List<Stylist> searchList = _db.Stylists.Include(stylists => stylists.Clients).ToList();
      List<Stylist> model = Stylist.Search(searchList, search);
      return View(model);
    }

  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Add a new Client</h2>
<hr />

@using (Html.BeginForm())
{
  <table class="set-table">
    <tr>
      <td>@Html.LabelFor(model => model.Name)</td>
      <td>@Html.TextBoxFor(model => model.Name, new { @required = "required"})</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Details)</td>
      <td>@Html.TextAreaFor(model => model.Details, new { @class="big-input"})</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Stylist)</td>
      <td>@Html.DropDownList("StylistId")</td>
    </tr>
  </table>
  <input type="submit" value="Add new client" class="btn btn-default" />
}

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this?</h2>
<hr />

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>@Html.DisplayFor(model => model.Name)</h2>
<hr />
<h4>@Html.DisplayNameFor(model => model.Details): @Html.DisplayFor(model => model.Details)</h4>

<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Edit</h2>
<hr />

<h4>Edit this Client: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  <table class="set-table">
    @Html.HiddenFor(model => model.ClientId)
    <tr>
      <td>@Html.LabelFor(model => model.Name)</td>
      <td>@Html.EditorFor(model => model.Name)</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Details)</td>
      <td>@Html.EditorFor(model => model.Details)</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Stylist)</td>
      <td>@Html.DropDownList("StylistId")</td>
    </tr>
  </table>
  <input type="submit" value="Save" />
}

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h2>Clients</h2>
<hr />

<div class="box">
  <div class="inner-box">
    @if (@Model.Count == 0)
    {
      <h3>No clients have been added yet!</h3>
    }

    @foreach (Client client in Model)
    {
      <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
    }
  </div>
</div>

HairSalon/Views/Clients/Search.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h2>Search Results</h2>
<hr />

<div class="box">
  <div class="inner-box">
    @if (@Model.Count == 0) 
    {
      <p>No clients matched!</p>
    }
    else
    {
      @foreach (Client client in Model)
      {
        <li>@Html.ActionLink($"{client.Name}", "Details", new {id = client.ClientId })</li>
      }
    }
  </div>
</div>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<img src="~/img/hair_salon.jpg">

HairSalon/Views/Shared/Footer.cshtml
<div id="footer" class="card">
  <h4>@Html.ActionLink("List of Stylists", "Index", "Stylists")</h4>
  <h4>@Html.ActionLink("List of Clients", "Index", "Clients")</h4>
  <h4>@Html.ActionLink("Home", "Index", "Home")</h4>
</div>

HairSalon/Views/Shared/Header.cshtml
<div id="header" class="jumbotron">
  <h1>Claire's Salon</h1>
  <form action="/Clients/Search" method="post">
    <label>Search for Client</label>
    <input class="input" type="text" id="search" name="search">
    <input type="submit" value="Search" class="btn btn-info buttons" />
  </form>
  <form action="/Stylists/Search" method="post">
    <label>Search for Stylist</label>
    <input class="input" type="text" id="search" name="search">
    <input type="submit" value="Search" class="btn btn-info buttons" />
  </form>
</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Claire's Salon</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css" type="text/css">
  </head>
  <body>
    <div class="container">
      @Html.Partial("Header")
      @RenderBody()
      @Html.Partial("Footer")
    </div>
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Add a new Stylist</h2>
<hr />

@using (Html.BeginForm())
{
  <table class="set-table">
    <tr>
      <td>@Html.LabelFor(model => model.Name)</td>
      <td>@Html.TextBoxFor(model => model.Name, new { @required = "required"} )</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Specialty)</td>
      <td>@Html.TextBoxFor(model => model.Specialty, new { @required = "required"} )</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Details)</td>
      <td>@Html.TextBoxFor(model => model.Details, new { @required = "required"} )</td>
    </tr>
  </table>
  <input type="submit" value="Add new Stylist" class="btn btn-default" />
}

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Are you sure you want to delete this?</h2>
<hr />

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
@using HairSalon.Models

<h2>@Html.DisplayFor(model => model.Name)</h2>
<hr />

<table class="set-table">
  <tr>
    <td>@Html.DisplayNameFor(model => model.Specialty):</td>
    <td>@Html.DisplayFor(model => model.Specialty)</td>
  </tr>
  <tr>
    <td>@Html.DisplayNameFor(model => model.Details):</td>
    <td>@Html.DisplayFor(model => model.Details)</td>
  </tr>
</table>

<div class="box">
  <div class="inner-box">
    @if (@Model.Clients.Count == 0)
    {
      <p>No clients have been added yet!</p>
    } 
    @foreach (Client client in Model.Clients)
    {
      <li>@Html.ActionLink($"{client.Name}", "Details", "Clients", new { id = client.ClientId})</li>
    }
  </div>
</div>

<div class="card">
  <p>@Html.ActionLink("Add new client", "Create", "Clients")</p>
  <p>@Html.ActionLink("Edit stylist", "Edit", new { id = Model.StylistId })</p>
  <p>@Html.ActionLink("Delete stylist", "Delete", new { id = Model.StylistId })</p>
</div>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit</h2>
<hr />

<h4>Edit this stylist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)
  <table class="set-table">
    <tr>
      <td>@Html.LabelFor(model => model.Name)</td>
      <td>@Html.EditorFor(model => model.Name, new { @required = "required"})</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Specialty)</td>
      <td>@Html.EditorFor(model => model.Specialty)</td>
    </tr>
    <tr>
      <td>@Html.LabelFor(model => model.Details)</td>
      <td>@Html.EditorFor(model => model.Details)</td>
    </tr>
  </table>
  <input type="submit" value="Save" />
}

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h2>Stylists</h2>
<hr />

<div class="box">
  <div class="inner-box">
    @if (@Model.Count == 0)
    {
      <p>No stylists have been added yet!</p>
    }
    @foreach (Stylist stylist in Model)
    {
      <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
    }
  </div>
</div>

<div class="card">
  <p>@Html.ActionLink("Add new Stylist", "Create")</p>
</div>

HairSalon/Views/Stylists/Search.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h2>Search Results</h2>
<hr />

<div class="box">
  <div class="inner-box">
    @if (@Model.Count == 0) 
    {
      <p>No stylists matched!</p>
    }
    else
    {
      @foreach (Stylist stylist in Model)
      {
        <li>@Html.ActionLink($"{stylist.Name}", "Details", new {id = stylist.StylistId })</li>
      }
    }
  </div>
</div>